In [1]:
import pandas as pd
data=pd.read_csv("http://bit.ly/imdbratings")

data.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [7]:
data.drop('content_rating',axis=1,inplace=True)
data.head()

   star_rating                     title   genre  duration
0          9.3  The Shawshank Redemption   Crime       142
1          9.2             The Godfather   Crime       175
2          9.1    The Godfather: Part II   Crime       200
3          9.0           The Dark Knight  Action       152
4          8.9              Pulp Fiction   Crime       154

In [8]:
l=['Rating','Title','Genre','Duration']
data.columns=l
data.head()

   Rating                     Title   Genre  Duration
0     9.3  The Shawshank Redemption   Crime       142
1     9.2             The Godfather   Crime       175
2     9.1    The Godfather: Part II   Crime       200
3     9.0           The Dark Knight  Action       152
4     8.9              Pulp Fiction   Crime       154

In [10]:
data1=data[data.Duration <= 100]
data1.head()

,Rating,Title,Genre,Duration
5,8.9,12 Angry Men,Drama,96
29,8.6,City Lights,Comedy,87
35,8.6,Modern Times,Comedy,87
48,8.5,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy,95
55,8.5,The Lion King,Animation,89

In [12]:
data1.sort_values('Rating',ascending=False)

,Rating,Title,Genre,Duration
5,8.9,12 Angry Men,Drama,96
35,8.6,Modern Times,Comedy,87
29,8.6,City Lights,Comedy,87
48,8.5,Dr. Strangelove or: How I Learned to Stop Worr...,Comedy,95
55,8.5,The Lion King,Animation,89
58,8.5,Paths of Glory,Drama,88
61,8.5,Grave of the Fireflies,Animation,89
88,8.4,The Kid,Comedy,68
98,8.4,Rashomon,Crime,88
90,8.4,Reservoir Dogs,Crime,99
64,8.4,WALL-E,Animation,98
87,8.4,Bicycle Thieves,Drama,93
63,8.4,M,Crime,99
127,8.3,Wild Strawberries,Drama,91
134,8.3,The Seventh Seal,Drama,96
131,8.3,My Neighbor Totoro,Animation,86
128,8.3,The Gold Rush,Adventure,95
101,8.3,Monty Python and the Holy Grail,Adventure,91
126,8.3,Up,Animation,96
117,8.3,Toy Story,Animation,81
105,8.3,The Third Man,Film-Noir,93
175,8.2,Touch of Evil,Crime,95
192,8.2,Finding Nemo,Animation,100
190,8.2,Life of Brian,Comedy,94
179,8.2,The Princess Bride,Adventure,98
178,8.2,The 400 Blows,Crime,99
176,8.2,Fargo,Crime,98
160,8.2,How to Train Your Dragon,Animation,98
174,8.2,Persona,Drama,83
172,8.2,Trainspotting,Drama,94
...,...,...,...,...
913,7.5,Suspiria,Horror,92
903,7.5,Heavenly Creatures,Biography,99
894,7.5,Source Code,Mystery,93
892,7.5,Fruitvale Station,Biography,85
886,7.5,Pi,Drama,84
883,7.5,A History of Violence,Crime,96
882,7.5,Mulan,Animation,88
881,7.5,The Texas Chain Saw Massacre,Horror,83
869,7.5,A Nightmare on Elm Street,Horror,91
864,7.5,[Rec],Horror,78
860,7.5,The Fly,Horror,96
853,7.5,L'illusionniste,Animation,80
844,7.5,Pinocchio,Animation,88
839,7.5,Bullets Over Broadway,Comedy,98
837,7.5,Menace II Society,Crime,97
835,7.5,Despicable Me 2,Animation,98
822,7.5,"Good Night, and Good Luck.",Drama,93
867,7.5,Best in Show,Comedy,90
948,7.4,Frances Ha,Comedy,86
966,7.4,The Simpsons Movie,Animation,87
962,7.4,Driving Miss Daisy,Comedy,99
959,7.4,Deconstructing Harry,Comedy,96
957,7.4,National Lampoon's Vacation,Comedy,98
938,7.4,Alice in Wonderland,Animation,75
947,7.4,Eraserhead,Drama,89
943,7.4,The Bucket List,Adventure,97
942,7.4,Raising Arizona,Comedy,94
939,7.4,Predestination,Drama,97
933,7.4,Beetlejuice,Comedy,92
971,7.4,Death at a Funeral,Comedy,90